import { StyleSheet } from "react-native";
import {
  ACCENT,
  BORDER,
  MUTED,
  RADIUS_MD,
  SPACE_1,
  SPACE_3,
  SPACE_4,
  SPACE_5,
  SPACE_6,
  SURFACE,
  TYPE_BODY,
  TYPE_CAPTION,
  fonts,
} from "@/constants/Variables";

export const legalDocumentStyles = StyleSheet.create({
  scrollContent: {
    paddingBottom: SPACE_6 + SPACE_1,
    paddingTop: SPACE_3,
  },
  section: { marginTop: 2 },
  sectionTitle: {
    color: MUTED,
    fontSize: TYPE_CAPTION + 1,
    fontFamily: fonts.medium,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginLeft: SPACE_5 + 1,
    marginBottom: SPACE_3 - 2,
    marginTop: SPACE_3 - 2,
  },
  card: {
    backgroundColor: SURFACE,
    marginHorizontal: SPACE_4 + SPACE_1,
    borderRadius: RADIUS_MD,
    padding: SPACE_4 + 2,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: BORDER,
  },
  text: {
    color: "white",
    fontFamily: fonts.medium,
    fontSize: TYPE_BODY,
    lineHeight: 24,
    marginBottom: 10,
  },
  bold: { fontFamily: fonts.heavy, color: "white" },
  bullets: { marginTop: 6 },
  bulletRow: { flexDirection: "row", alignItems: "flex-start", marginBottom: 10 },
  bulletDot: { color: ACCENT, marginRight: 10, fontSize: 18, lineHeight: 22 },
  bulletText: {
    color: "white",
    fontFamily: fonts.medium,
    fontSize: TYPE_BODY,
    lineHeight: 24,
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  lastUpdated: {
    color: "#A8A8A8",
    fontFamily: fonts.medium,
    fontSize: TYPE_CAPTION + 1,
    lineHeight: 18,
    marginTop: 24,
    marginHorizontal: SPACE_5 + 1,
  },
  footerSpace: { height: SPACE_5 },
});
