import {
  ACCENT,
  ON_ACCENT_TEXT,
  RADIUS_LG,
  cardMetaText,
  cardTitleText,
  detailSectionTitle,
  fonts,
  listRowTitleText,
  listSectionTitle,
  searchPlaceholderText,
  TYPE_CAPTION,
  TYPE_SECTION,
} from "@/constants/Variables";
import { StyleSheet } from "react-native";

export const GROUP_SURFACE = "#0E1012";
export const GROUP_BORDER = "rgba(255,255,255,0.06)";
export const GROUP_ROW_INSET = 72;

export const groupsPageStyles = StyleSheet.create({
  scrollContent: {
    flexGrow: 1,
    paddingTop: 2,
    gap: 28,
  },
  section: {
    gap: 12,
  },
  sectionHeader: {
    marginBottom: 2,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitleStart: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  sectionTitle: {
    ...listSectionTitle,
    fontSize: TYPE_SECTION,
    lineHeight: 26,
  },
  sectionAddBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1.5,
    borderColor: ACCENT,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  sectionSubtitle: {
    ...searchPlaceholderText,
    lineHeight: 19,
    paddingRight: 8,
  },
  infoBtn: {
    alignItems: "center",
    justifyContent: "center",
    padding: 4,
  },
  circleCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: GROUP_SURFACE,
    borderRadius: RADIUS_LG,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: GROUP_BORDER,
  },
  circleCardMain: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
  },
  circleCardTitle: {
    ...cardTitleText,
    marginBottom: 2,
  },
  circleCardMeta: {
    ...cardMetaText,
  },
  browseRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: GROUP_SURFACE,
    borderRadius: RADIUS_LG,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: GROUP_BORDER,
  },
  browseRowIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  browseRowTitle: {
    ...listRowTitleText,
    flex: 1,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minHeight: 42,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: GROUP_SURFACE,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.08)",
  },
  searchBarPlaceholder: {
    ...searchPlaceholderText,
    flex: 1,
  },
  subsectionTitle: {
    ...detailSectionTitle,
    fontSize: 15,
    marginTop: 4,
  },
  discoverScroll: {
    marginHorizontal: -20,
    paddingHorizontal: 20,
  },
  discoverCard: {
    width: 168,
    padding: 14,
    marginRight: 12,
    backgroundColor: GROUP_SURFACE,
    borderRadius: RADIUS_LG,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: GROUP_BORDER,
  },
  discoverCardIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    marginBottom: 12,
  },
  discoverCardCover: {
    width: 44,
    height: 44,
    borderRadius: 12,
    marginBottom: 12,
    backgroundColor: "#1C1C1E",
  },
  discoverCardTitle: {
    ...cardTitleText,
    fontFamily: fonts.heavy,
    fontSize: 15,
    letterSpacing: 0.05,
    marginBottom: 4,
  },
  discoverCardTag: {
    alignSelf: "flex-start",
    fontFamily: fonts.medium,
    fontSize: TYPE_CAPTION - 2,
    color: ACCENT,
    letterSpacing: 0.3,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  discoverCardMeta: {
    ...cardMetaText,
    fontSize: TYPE_CAPTION - 1,
    marginBottom: 12,
  },
  joinBtn: {
    alignSelf: "flex-start",
    minWidth: 64,
    height: 32,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: ACCENT,
    alignItems: "center",
    justifyContent: "center",
  },
  joinBtnText: {
    fontFamily: fonts.medium,
    fontSize: TYPE_CAPTION,
    color: ON_ACCENT_TEXT,
    letterSpacing: 0.04,
  },
  joinBtnDisabled: {
    opacity: 0.55,
  },
  communityListSurface: {
    backgroundColor: GROUP_SURFACE,
    borderRadius: RADIUS_LG,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: GROUP_BORDER,
    overflow: "hidden",
  },
  communityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 13,
    paddingHorizontal: 16,
    backgroundColor: GROUP_SURFACE,
  },
  communityRowMainTouchable: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    minWidth: 0,
  },
  communityRowMain: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
  },
  communityRowTitle: {
    ...listRowTitleText,
    fontFamily: fonts.heavy,
    marginBottom: 2,
  },
  communityRowMeta: {
    ...cardMetaText,
  },
  rowSeparator: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: GROUP_BORDER,
    marginLeft: GROUP_ROW_INSET,
  },
  loadingInline: {
    paddingVertical: 24,
    alignItems: "center",
  },
});
